### PR TITLE
Add details about entry `data`

### PR DESCRIPTION
**Pull request by mixmix**
I found myself console.logging to figure out what data I could play with in some of the methods
This is me noting what I've seen
I think this is important so people know the `entries` are not isomorphic

:fire:  NOTE some of this is best-guess (even more reason to try documenting), and there's definitely parts missing in this.

### CODE REVIEW

**Comment by mixmix** [comment]
Request - specifically I want to know whether it's ok to lean on `type` and `inferredType` and what the difference is, and when I can expect to see one or the other. Like for `peers()` will it give me a type if it is known, and if not does it fall back to `inferredType`?

**Comment by staltz** [comment]
Great PR! Actually I'm waiting for feedback from you and others who maintain Patchbay and Patchwork before publishing ssb-conn v1.0.0, so now is the time to make this module *feel right*.

Most of your guesses were correct. I'll edit this file in such a way that answers your questions, you'll then see from my commit what that is.

**Comment by staltz** [comment]
And in general, do you have feedback about the API? I was thinking that maybe `ssb.conn.peers()` is a confusing API, maybe it should be `hubPeers()`? So that it's always clear what the pool is:

- `dbPeers()`
- `hubPeers()`
- `stagedPeers()`

Also I'm considering whether to rename `birth` to `dbBirth` so there is the same symmetry:

- `dbBirth`
- `hubBirth`
- `stagingBirth`

**Comment by mixmix** [comment]
@staltz  I like `dbBirth`

I don't know what "hub" means ... I seem to remember it's an internal thing. what I'd be looking for is : 
- persisted peers (db is fine too)
- connected peers / current peers ... who am I currently gossiping with
- ready peers / peers I could connect to.

**Comment by staltz** [comment]
Mix that's a quite accurate intuition:

- persisted peers (db is fine too)
  - **ConnDB**
  - A cold storage of fixed (multiserver) addresses of other peers and additional metadata
- connected peers / current peers ... who am I currently gossiping with
  - **ConnHub**
  - a hot collection of peers connected, or in transient connection (either connec**ting** or disconnecting)
- ready peers / peers I could connect to.
  - **ConnStaging**
  - a "lukewarm" collection of peers that we'd like to show to the user so they can decide whether to connect to these (and move them into ConnHub) 

Does this answer what you want? By the way, I'll merge this (it has commits from both of us).

**Comment by staltz** [comment]
PS: what about the [Learn More](https://github.com/staltz/ssb-conn#learn-more) section? Was that helpful?

**Comment by mixmix** [comment]
Yeah that was useful (learn more).

My main feedback is that "hub" is not intuitive for what's more like
"current" or "live". Huh just sounds like what everything is connecting
to...

Caught a typo in learn more:
ConnDB contains metadata on stable servers and peers that have been
successfully ~~connectable~~ connected to

**Pull request merged**
